mysite/basics/urls.py
from django.conf.urls import url

import basics.views.auth as auth_views
import basics.views.contact as contact_views
import basics.views.other as other_views
import basics.views.tags as tags_views
from .views import api as api_views
from .views import tasks as tasks_views

app_name = 'basics'

urlpatterns = [
    url(r'^$', other_views.index, name='index'),

    url(r'^vuetest/$', other_views.vuetest, name='vuetest'),

    url(r'^contact/all/$', contact_views.all_contacts, name='contact-all'),
    url(r'^contact/add/$', contact_views.AddContactView.as_view(), name='contact-add'),
    url(r'^contact/details/(?P<pk>[-\w]+)/$', contact_views.ContactDetailView.as_view(),
        name='contact-details'),

    url(r'^tags/$', tags_views.TagsView.as_view(), name='tags'),
    url(r'^tags/add/$', tags_views.AddTagsView.as_view(), name='tags-add'),

    url(r'^auth/login/$', auth_views.MyLoginView.as_view(), name='login'),
    url(r'^auth/logout/$', auth_views.logout_view, name='logout'),

    # APIcelery_test
    url(r'^api/hello', api_views.hello_world, name='api_hello'),
    url(r'^tasks/test', tasks_views.celery_test, name='celery_test'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from rest_framework import urls as  drf_urls

from basics.views.rapi import router
from basics import urls as basics_urls

from rest_framework.schemas import get_schema_view

schema_view = get_schema_view(title='Pastebin API')

urlpatterns = [
    url(r'^', include(basics_urls)),

    url(r'^admin/', admin.site.urls),

    url(r'^rapi/', include(router.urls)),
    url(r'^api-auth/', include(drf_urls)),
    url(r'^schema/$', schema_view),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/basics/models.py
from django.db import models
from django.contrib.auth.models import User


class IntrospectionMixin:
    @classmethod
    def field_list(cls, include_hidden=False, exclude=()):
        fields = cls._meta.get_fields(include_hidden=include_hidden)
        return [f.name for f in fields if f.name not in exclude]


class Tag(models.Model, IntrospectionMixin):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Contact(models.Model, IntrospectionMixin):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=30)

    email = models.EmailField(max_length=50, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)

    profile_pic = models.ImageField(upload_to='profile', blank=True, null=True)

    tags = models.ManyToManyField(Tag, related_name='contacts', blank=True)
    user = models.ForeignKey(User, related_name='contacts')

mysite/basics/forms.py
from django import forms

import basics.models as db_models


class ContactForm(forms.ModelForm):
    class Meta:
        model = db_models.Contact
        exclude = ('id','user', )


class TagsAddForm(forms.ModelForm):
    class Meta:
        model = db_models.Tag
        exclude = ('id',)

mysite/basics/views/api.py
from django.http import JsonResponse
from rest_framework.decorators import api_view


# @csrf_exempt
@api_view(['GET', 'POST'])
def hello_world(request):
    print(request.data)
    return JsonResponse({'message': 'Hello world!'})

mysite/basics/views/contact.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

import basics.models as models
import basics.forms as forms


class ContactDetailView(DetailView, LoginRequiredMixin):
    template_name = 'basics/contact/details.html'
    model = models.Contact

    def get_queryset(self):
        return self.model.objects.prefetch_related('tags')


class AddContactView(View, LoginRequiredMixin):
    template = 'basics/contact/add.html'

    def get(self, request):
        form = forms.ContactForm()
        return render(request, self.template, {'form': form})

    def post(self, request):
        form = forms.ContactForm(request.POST, request.FILES)
        if form.is_valid():
            contanct = form.save(commit=False)
            contanct.user = request.user
            contanct.save()
            form.save_m2m()
            return HttpResponseRedirect(reverse('basics:contact-all'))

        return render(request, self.template, {'form': form})

@login_required
def all_contacts(request):
    contacts = models.Contact.objects.filter(user=request.user)
    return render(request, 'basics/contact/list.html', {'contacts': contacts})

mysite/basics/views/other.py
from django.shortcuts import render


def index(request):
    return render(request, 'basics/index.html')


def vuetest(request):
    return render(request, 'basics/vuetest.html')

mysite/basics/views/rapi.py
from django.contrib.auth.models import User, Group
from rest_framework import viewsets, routers

from ..serializers import UserSerializer, GroupSerializer, ContactSerializer, TagSerializer
from ..models import Contact, Tag


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all().prefetch_related('groups').order_by('-date_joined')
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    queryset = Group.objects.all()
    serializer_class = GroupSerializer


class ContactViewSet(viewsets.ModelViewSet):
    queryset = Contact.objects.all().select_related('user').prefetch_related('tags', 'user__groups')
    serializer_class = ContactSerializer


class TagViewSet(viewsets.ModelViewSet):
    queryset = Tag.objects.all()
    serializer_class = TagSerializer


router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'tags', TagViewSet)
router.register(r'contacts', ContactViewSet)

mysite/basics/views/tags.py
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View

from basics.forms import TagsAddForm
from basics.models import Tag


class TagsView(View):
    def get(self, request):
        tags_counts = Tag.objects.values('name').annotate(count=Count('contacts__id'))
        return render(request, 'basics/tags/stats.html', {'tags_counts': tags_counts})


class AddTagsView(View):
    template_name = 'basics/tags/add.html'

    def render_form(self, request, form):
        return render(request, self.template_name, {'form': form})

    def get(self, request):
        form = TagsAddForm()
        return self.render_form(request, form)

    def post(self, request):
        form = TagsAddForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('basics:tags'))
        return self.render_form(request, form)

mysite/basics/views/tasks.py
from django.shortcuts import render

from .. import tasks


def celery_test(request):
    tasks.queue_test.delay()

    result = tasks.celery_app_test.delay()
    tags = result.get()

    return render(request, 'basics/tasks/test.html', {'tags': tags})

mysite/basics/templates/basics/_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'basics/css/bootstrap.css' %}"/>
</head>
<body>
{% include 'basics/_navbar.html' %}

<div class="container">
    {% block content %}
        Default content
    {% endblock %}
</div>

</body>

<script src="{% static 'basics/js/jquery-3.2.1.js' %}"></script>
<script src="{% static 'basics/js/bootstrap.js' %}"></script>
<script src="{% static 'basics/js/vue.js' %}"></script>

{% block js %}
{% endblock %}

</html>

mysite/basics/templates/basics/_navbar.html
<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'basics:index' %}">MYSITE</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'basics:contact-all' %}">Contacts</a></li>
                <li><a href="{% url 'basics:tags' %}">Tags</a></li>
                <li><a href="{% url 'basics:vuetest' %}">Vue Test</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Tasks <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'basics:celery_test' %}">Celery test</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'basics:logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'basics:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

mysite/basics/templates/basics/contact/add.html
{% extends 'basics/_layout.html' %}

{% block title %}Add contact{% endblock %}

{% block content %}
    <form class="form-horizontal" action="{% url 'basics:contact-add' %}"
          method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-default" type="submit" value="Submit"/>
    </form>
{% endblock %}

mysite/basics/templates/basics/contact/all.html
{% extends 'basics/_layout.html' %}

{% block title %}All contacts{% endblock %}

{% block content %}

    <h3>All my contacts</h3>

    <ul class="list-unstyled">
        {% for c in contacts %}
            <li><a href="{% url 'basics:contact-details' pk=c.id %}"> {{ c.first_name }} {{ c.last_name }}</a></li>
        {% endfor %}
    </ul>

    <p><a class="btn btn-default" href="{% url 'basics:contact-add' %}">Add contact</a></p>

{% endblock %}

mysite/basics/templates/basics/contact/details.html
{% extends 'basics/_layout.html' %}

{% block title %}Contact details{% endblock %}

{% block content %}
    First name: {{ object.first_name }}<br/>
    Last name: {{ object.last_name }}<br/>
    Email: {{ object.email }} <br/>
    Phone: {{ object.phone }} <br/>

    <span>Tags:</span>
    {% for tag in object.tags.all %}
        <span class="badge">{{ tag.name }}</span>
    {% endfor %}

    {% if object.profile_pic %}
        <img src="{{ object.profile_pic.url }}" alt="Client Photo">
    {% endif %}

{% endblock %}

mysite/basics/templates/basics/contact/list.html
{% extends 'basics/_layout.html' %}

{% block title %}All contacts{% endblock %}

{% block content %}

    <h3>All my contacts</h3>

    <ul class="list-unstyled">
        {% for c in contacts %}
            <li><a href="{% url 'basics:contact-details' pk=c.id %}"> {{ c.first_name }} {{ c.last_name }}</a></li>
        {% endfor %}
    </ul>

    <p><a class="btn btn-default" href="{% url 'basics:contact-add' %}">Add contact</a></p>

{% endblock %}

mysite/basics/templates/basics/index.html
{% extends 'basics/_layout.html' %}

{% block title %}Hello to the basic site!{% endblock %}

{% block content %}
    <p>Hi there!</p>
{% endblock %}

mysite/basics/templates/basics/tags/add.html
{% extends 'basics/_layout.html' %}

{% block title %}Add tag{% endblock %}

{% block content %}

    <form action="{% url 'basics:tags-add' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit"/>
    </form>

{% endblock %}

mysite/basics/templates/basics/tags/stats.html
{% extends 'basics/_layout.html' %}

{% block title %}Tags{% endblock %}

{% block content %}
    <ul class="list-unstyled">
        {% for tag_stats in tags_counts %}
            <li>{{ tag_stats.name }}:{{ tag_stats.count }}</li>
        {% endfor %}
    </ul>

    <a class="btn btn-default" href="{% url 'basics:tags-add' %}">Add</a>
{% endblock %}

mysite/basics/templates/basics/tasks/test.html
{% extends 'basics/_layout.html' %}

{% block title %}Celery task tests{% endblock %}

{% block content %}
    <h2>Celery Tests</h2>
    <p>Tag names fetched by celery task</p>
    <ul>
    {% for t in tags %}
        <li>{{ t }}</li>
    {% endfor %}
    </ul>
{% endblock %}

mysite/basics/templates/basics/vuetest.html
{% extends 'basics/_layout.html' %}

{% block content %}
    {% verbatim js %}

        <div id="app">
            <p>This is a VueJS App</p>
            {{ message }}
        </div>

    {% endverbatim js %}
{% endblock %}

{% block js %}
    <script>
        var app = new Vue({
            el: '#app',
            data: {
                message: 'Hello Vue!'
            }
        })
    </script>
{% endblock %}